[package]
name = "automata-rpc"
version = "0.1.0"
authors = ["Automata Team"]
edition = "2018"
license = "Apache-2.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde_json = { version = "1" }
serde = { version = "1.0.119", features = ["derive"] }
sp-core = {version  = "3.0.0", default-features = false }
jsonrpc-core = '15.1.0'
jsonrpc-derive = '15.0.0'
jsonrpc-core-client = "15.0.0"
sp-api = '3.0.0'
sp-blockchain = '3.0.0'
sp-block-builder = '3.0.0'
sc-rpc-api = '0.9.0'
sp-transaction-pool = '3.0.0'
sc-network = '0.9.0'
jsonrpc-pubsub = "15.1.0"
sc-rpc = '3.0.0'
sc-client-api = '3.0.0'
sp-runtime = '3.0.0'
substrate-frame-rpc-system = '3.0.0'
pallet-transaction-payment-rpc = '3.0.0'
sc-light = '3.0.0'
hex = '0.4.3'
sp-std = '3.0.0'
frame-system-rpc-runtime-api = { default-features = false, version = '3.0.0' }
sp-core = { features = ["full_crypto"], version = '3.0.0' }

# local dependencies
automata-primitives = { path = "../primitives" }
automata-runtime = { path = '../runtime' }
pallet-geode = { path = "../pallets/geode" }
pallet-transfer = { path = "../pallets/transfer" }

fc-rpc = { default-features = false, version = '1.0.0'}
fc-rpc-core = { default-features = false, version = '1.0.0'}
fc-db = { default-features = false, version = '1.0.0'}
fp-rpc = { default-features = false, version = '1.0.0'}
pallet-ethereum = { default-features = false, version = '1.0.0'}