name: Publish release runtime

on:
  push:
    tags:
      # Catches v1.2.3 and v1.2.3-rc1
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  build-wasm:
    name: Build wasm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build wasm
        env:
          SR_TOOL_TAG: 1.53.0
        run: |
          scripts/setup-wasm.sh
      - name: Upload deploy
        uses: actions/upload-artifact@v2
        with:
          name: automata-artifact
          path: deploy


  complete-build:
    name: Complete build
    runs-on: ubuntu-latest
    needs: [build-wasm]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: automata-artifact
          path: deploy

      - name: Complete build
        run: scripts/complete-build.sh

      - name: Publish github release
        uses: docker://antonyurchenko/git-release:latest
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: "false"
          PRE_RELEASE: "false"
          CHANGELOG_FILE: "CHANGELOG.md"
          ALLOW_EMPTY_CHANGELOG: "true"
        with:
          args: |
            deploy/bin/*